name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run make 
      run: make
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: my-artifact
        path: exec
        retention-days: 1
      
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: my-artifact
          path: exec
          
      - name: Change permissions
        run: chmod 755 exec/*
     
      - name: Ls exec
        run: ls -l exec
      
      - name: Run test 1
        run: ./exec/hello

  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
        
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: my-artifact
          path: exec
          
      - name: Change permissions
        run: chmod 755 exec/*
    
      - name: Ls exec
        run: ls -l exec
      
      - name: Run test 2
        run: ./exec/hello
      
