name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Run make 
      run: make
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: exec
        # The desired behavior if no files are found using the provided path.
    Available Options:
      warn: Output a warning but do not fail the action
        # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
        retention-days: 1    

